name: starterkit_app
description: A new Flutter project.
publish_to: "none"
version: 0.0.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  auto_route: ^11.1.0
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  context_plus: ^6.0.6
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  equatable: ^2.0.7
  file: ^7.0.1
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  meta: ^1.17.0
  path: ^1.9.1
  path_provider: ^2.1.5
  platform: ^3.1.6
  retrofit: ^4.9.1
  uuid: ^4.5.2

dev_dependencies:
  auto_route_generator: ^10.3.1
  build_runner: ^2.10.4
  drift_dev: ^2.30.0
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  full_coverage: ^1.0.0
  injectable_generator: ^2.12.0
  intl_utils: ^2.8.13
  json_serializable: ^6.11.3
  mockito: ^5.6.1
  retrofit_generator: ^10.2.1

dependency_overrides:
  analyzer: ^8.2.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  uses-material-design: true

flutter_gen:
  output: lib/common/resources
  line_length: 120
  fonts:
    enabled: false

flutter_intl:
  enabled: true
  class_name: Il8n
  arb_dir: lib/common/localization
  output_dir: lib/common/localization/generated
